emotion_model:
  name: "wav2vec2-large-xlsr-53"
  huggingface_id: "/nfs/scratch/jtan/models/wav2vec2-large-xlsr-53"
  task: "feature-extraction"
  
audio_processing:
  sample_rate: 16000
  segment_length: 30  # seconds
  overlap: 15         # seconds
  min_segment_length: 5  # seconds
  
feature_extraction:
  batch_size: 8
  device: "cuda"
  output_dir: "./data/processed/emotion_features/"
