audio_processing:
  sample_rate: 16000
  segment_length: 30         # seconds
  overlap: 15                # seconds

emotion_model:
  # Default to SpeechBrain (if --repo is passed via command line, use HuggingFace)
  huggingface_id: "speechbrain/emotion-recognition-wav2vec2-IEMOCAP"

runtime:
  segments_per_batch: 8      # "If insufficient GPU memory, reduce to 4/2
  fp16: true                 # Recommended to enable on GPU
